
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-19T21:12:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8355787a1024c56ee87cbb76a41654e6d0c63725",
 "version": "4.1.1a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
